#pragma once
// PLAYSCENE
#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6
#define SCENE_SECTION_MAP	7
#define SCENE_SECTION_GRID	8

#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS_GREEN_WALK	3
#define OBJECT_TYPE_RECTANGLE	5
#define OBJECT_TYPE_NO_COLLISION_OBJECTS 4
#define OBJECT_TYPE_PIPE_NORMAL 6
#define OBJECT_TYPE_KOOPAS_GREEN_FLY	7
#define OBJECT_TYPE_KOOPAS_RED_WALK	8
#define OBJECT_TYPE_KOOPAS_RED_FLY	9
#define OBJECT_TYPE_COIN_NORMAL	10
#define OBJECT_TYPE_GOOMBA_RED_FLY	11
#define OBJECT_TYPE_FIRE_BULLET	12
#define OBJECT_TYPE_FLOWER_RED		13
#define OBJECT_TYPE_FLOWER_BULLET	14
#define OBJECT_TYPE_QUESTION_BRICK_NORMAL	15
#define OBJECT_TYPE_LEAF	16
#define OBJECT_TYPE_MUSHROOM_RED		17
#define OBJECT_TYPE_QUESTION_BRICK_HAVE_LEAF	18
#define OBJECT_TYPE_MUSHROOM_GREEN		19
#define OBJECT_TYPE_QUESTION_BRICK_JUST_HAVE_MUSHROOM	20
#define OBJECT_TYPE_FLOWER_GREEN				21
#define OBJECT_TYPE_FLOWER_GREEN_CAN_SHOOT		22
#define OBJECT_TYPE_BREAKABLE_BRICK_NORMAL	23
#define OBJECT_TYPE_BREAKABLE_BRICK_BELL	25
#define OBJECT_TYPE_BELL	24
#define OBJECT_TYPE_COIN_CAN_TOSS	26
#define OBJECT_TYPE_HUD	27
#define OBJECT_TYPE_SPECIAL_ITEM	28
#define OBJECT_TYPE_PIPE_CAN_SLIDE_DOWN 29
#define OBJECT_TYPE_PIPE_CAN_SLIDE_UP 30
#define OBJECT_TYPE_BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_TOP				31
#define OBJECT_TYPE_BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_TOP			32
#define OBJECT_TYPE_BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_BOTTOM			33
#define OBJECT_TYPE_BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_BOTTOM			34
#define OBJECT_TYPE_SCORE_AND_1LV		35
#define OBJECT_TYPE_CAMERA		36
#define OBJECT_TYPE_QUESTION_BRICK_MULTI_COIN		48
#define OBJECT_TYPE_FLOATING_WOOD		49
#define OBJECT_TYPE_BOOMERANG											50
#define OBJECT_TYPE_BOOMERANG_ENEMY										51
#define OBJECT_TYPE_HIT_EFFECT_FIRE_BULLET 52
#define	OBJECT_TYPE_HIT_EFFECT_TURN_TAIL 53
#define OBJECT_TYPE_PORTAL	100

#define MAX_SCENE_LINE 1024
#define MAX_POWER_SPEED_UP 7
#define	TIME_PER_LEVEL_SPEED_UP 200
// ID MAP
#define ID_MAP_1	3
#define ID_MAP_4	4
#define	ID_WORLD_MAP	2
#define ID_INTRO_SCENE 1
#define MOVE_CAM_X_VX		0.1f

#define IN_USE_WIDTH		330
#define IN_USE_HEIGHT		300


#define GRID_SECTION_SETTINGS	1
#define GRID_SECTION_OBJECTS	2

#define GRID_SECTION_SETTINGS	1
#define GRID_SECTION_OBJECTS	2
#define MAX_GRID_LINE 1024
// LITMIT MAP 1
#define LIMIT_X_MAP_1	2649
#define	POS_X_TUNNEL	1300
#define POS_Y_TUNNEL	980
#define	POS_X_AUTOWALK_CAM_END	2500
#define POS_Y_AUTOWALK_CAM_END	-62
/// LITMIT MAP 4
#define POS_X_CAM_STOP_MOVE	1870
#define V_CAM_MOVE	0.035f
#define	POS_Y_MAP_4	210
#define LIMIT_X_MAP_4	2408
#define POS_X_AUTOWALK_CAM_END_2	2243
// MARIO
#define MARIO_WALKING_SPEED		0.1f 


#define MARIO_JUMP_SPEED_Y		0.5f
#define MARIO_JUMP_DEFLECT_SPEED 0.2f
#define MARIO_GRAVITY			0.002f
#define MARIO_DIE_DEFLECT_SPEED	 0.5f

#define MARIO_STATE_IDLE			0
#define MARIO_STATE_WALKING_RIGHT	150
#define MARIO_STATE_WALKING_LEFT	250
#define MARIO_STATE_JUMP			300
#define MARIO_STATE_DIE				400
#define MARIO_STATE_FLY	500
//#define MARIO_STATE_FLYING_LEFT		600
#define MARIO_STATE_BRAKING_RIGHT	700	
#define MARIO_STATE_BRAKING_LEFT	800
#define MARIO_STATE_HOLDING_RIGHT	900
#define MARIO_STATE_HOLDING_LEFT	1000
#define MARIO_STATE_HOLDING_NOTHING	1100
#define MARIO_STATE_KICK			1200
#define MARIO_STATE_RUNNING_RIGHT	1300
#define MARIO_STATE_RUNNING_LEFT	1400
#define MARIO_STATE_SITDOWN			1500
#define MARIO_STATE_SPEEDING_DOWN	1600
#define MARIO_STATE_TURNING_TAIL	1700
#define MARIO_STATE_FALL_DOWN	1800
#define	MARIO_STATE_PIPE_SLIDE_DOWN 1900
#define MARIO_STATE_PIPE_SLIDE_UP	2000



#define MARIO_ANI_BIG_IDLE_RIGHT		0
#define MARIO_ANI_BIG_IDLE_LEFT			1
#define MARIO_ANI_BIG_WALKING_RIGHT		2	
#define MARIO_ANI_BIG_WALKING_LEFT		3
#define MARIO_ANI_BIG_JUMPING_RIGHT		4
#define MARIO_ANI_BIG_JUMPING_LEFT		5
#define MARIO_ANI_BIG_FLYING_RIGHT		6	
#define MARIO_ANI_BIG_FLYING_LEFT		7
#define MARIO_ANI_BIG_BRAKING_RIGHT		8	
#define MARIO_ANI_BIG_BRAKING_LEFT		9
#define MARIO_ANI_BIG_HOLDING_RIGHT		10	
#define MARIO_ANI_BIG_HOLDING_LEFT		11
#define MARIO_ANI_BIG_KICKING_RIGHT		12	
#define MARIO_ANI_BIG_KICKING_LEFT		13
#define MARIO_ANI_BIG_RUNNING_RIGHT		14	
#define MARIO_ANI_BIG_RUNNING_LEFT		15
#define MARIO_ANI_BIG_SITDOWN_RIGHT		16	
#define MARIO_ANI_BIG_SITDOWN_LEFT		17

#define MARIO_ANI_SMALL_IDLE_RIGHT			20
#define MARIO_ANI_SMALL_IDLE_LEFT			21
#define MARIO_ANI_SMALL_WALKING_RIGHT		22	
#define MARIO_ANI_SMALL_WALKING_LEFT		23
#define MARIO_ANI_SMALL_JUMPING_RIGHT		24
#define MARIO_ANI_SMALL_JUMPING_LEFT		25
#define MARIO_ANI_SMALL_FLYING_RIGHT		26	
#define MARIO_ANI_SMALL_FLYING_LEFT			27
#define MARIO_ANI_SMALL_BRAKING_RIGHT		28	
#define MARIO_ANI_SMALL_BRAKING_LEFT		29
#define MARIO_ANI_SMALL_HOLDING_RIGHT		30	
#define MARIO_ANI_SMALL_HOLDING_LEFT		31
#define MARIO_ANI_SMALL_KICKING_RIGHT		32	
#define MARIO_ANI_SMALL_KICKING_LEFT		33
#define MARIO_ANI_SMALL_RUNNING_RIGHT		34	
#define MARIO_ANI_SMALL_RUNNING_LEFT		35



#define MARIO_ANI_TAIL_IDLE_RIGHT		40
#define MARIO_ANI_TAIL_IDLE_LEFT		41
#define MARIO_ANI_TAIL_WALKING_RIGHT	42	
#define MARIO_ANI_TAIL_WALKING_LEFT		43
#define MARIO_ANI_TAIL_JUMPING_RIGHT	44
#define MARIO_ANI_TAIL_JUMPING_LEFT		45
#define MARIO_ANI_TAIL_FLYING_RIGHT		46	
#define MARIO_ANI_TAIL_FLYING_LEFT		47
#define MARIO_ANI_TAIL_BRAKING_RIGHT	48	
#define MARIO_ANI_TAIL_BRAKING_LEFT		49
#define MARIO_ANI_TAIL_HOLDING_RIGHT	50	
#define MARIO_ANI_TAIL_HOLDING_LEFT		51
#define MARIO_ANI_TAIL_KICKING_RIGHT	52	
#define MARIO_ANI_TAIL_KICKING_LEFT		53
#define MARIO_ANI_TAIL_RUNNING_RIGHT	54	
#define MARIO_ANI_TAIL_RUNNING_LEFT		55
#define MARIO_ANI_TAIL_SITDOWN_RIGHT	56
#define MARIO_ANI_TAIL_SITDOWN_LEFT		57
#define MARIO_ANI_TAIL_TURNING_RIGHT	58	
#define MARIO_ANI_TAIL_TURNING_LEFT		59


#define MARIO_ANI_FIRE_IDLE_RIGHT		60
#define MARIO_ANI_FIRE_IDLE_LEFT		61
#define MARIO_ANI_FIRE_WALKING_RIGHT	62	
#define MARIO_ANI_FIRE_WALKING_LEFT		63
#define MARIO_ANI_FIRE_JUMPING_RIGHT	64
#define MARIO_ANI_FIRE_JUMPING_LEFT		65
#define MARIO_ANI_FIRE_FLYING_RIGHT		66	
#define MARIO_ANI_FIRE_FLYING_LEFT		67
#define MARIO_ANI_FIRE_BRAKING_RIGHT	68	
#define MARIO_ANI_FIRE_BRAKING_LEFT		69
#define MARIO_ANI_FIRE_HOLDING_RIGHT	70
#define MARIO_ANI_FIRE_HOLDING_LEFT		71
#define MARIO_ANI_FIRE_KICKING_RIGHT	72	
#define MARIO_ANI_FIRE_KICKING_LEFT		73
#define MARIO_ANI_FIRE_RUNNING_RIGHT	74	
#define MARIO_ANI_FIRE_RUNNING_LEFT		75
#define MARIO_ANI_FIRE_SITDOWN_RIGHT	76
#define MARIO_ANI_FIRE_SITDOWN_LEFT		77
#define MARIO_ANI_FIRE_FIRING_BULLET_LEFT	79
#define MARIO_ANI_FIRE_FIRING_BULLET_RIGHT	78

#define MARIO_ANI_BIG_MAX_SPEED_RIGHT	80
#define MARIO_ANI_BIG_MAX_SPEED_LEFT	81
#define MARIO_ANI_FIRE_MAX_SPEED_RIGHT	82
#define MARIO_ANI_FIRE_MAX_SPEED_LEFT	83
#define MARIO_ANI_SMALL_MAX_SPEED_RIGHT	84
#define MARIO_ANI_SMALL_MAX_SPEED_LEFT	85
#define MARIO_ANI_TAIL_MAX_SPEED_RIGHT	86
#define MARIO_ANI_TAIL_MAX_SPEED_LEFT	87
#define MARIO_ANI_FALLING_LEFT			88
#define MARIO_ANI_FALLING_RIGHT			89

#define MARIO_ANI_DIE					90
#define MARIO_ANI_SMALL_PIPE		91
#define MARIO_ANI_BIG_PIPE			92
#define MARIO_ANI_TAIL_PIPE						93
#define MARIO_ANI_FIRE_PIPE						94

#define MARIO_TRANSFORM_LEFT					95
#define MARIO_TRANSFORM_RIGHT					96

#define MARIO_SMOKE_TRANSFORM_LEFT				97
#define MARIO_SMOKE_TRANSFORM_RIGHT				98

#define MARIO_ANI_BIG_JUMP_MAX_POWER_RIGHT			99
#define MARIO_ANI_BIG_JUMP_MAX_POWER_LEFT			100
#define MARIO_ANI_SMALL_JUMP_MAX_POWER_RIGHT		101
#define MARIO_ANI_SMALL_JUMP_MAX_POWER_LEFT		    102
#define MARIO_ANI_TAIL_JUMP_MAX_POWER_RIGHT			103
#define MARIO_ANI_TAIL_JUMP_MAX_POWER_LEFT			104
#define MARIO_ANI_FIRE_JUMP_MAX_POWER_RIGHT			105
#define MARIO_ANI_FIRE_JUMP_MAX_POWER_LEFT			106

#define	MARIO_LEVEL_BIG		2
#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_TAIL	3
#define	MARIO_LEVEL_FIRE	4

#define MARIO_BIG_BBOX_WIDTH  15
#define MARIO_BIG_BBOX_HEIGHT 27

#define MARIO_SMALL_BBOX_WIDTH  13
#define MARIO_SMALL_BBOX_HEIGHT 15
#define MARIO_TURNING_BONUS_HEIGHT 8
#define MARIO_UNTOUCHABLE_TIME 3000
#define MARIO_KICK_TIME 300
#define MARIO_TURNING_TIME		 500
#define MARIO_FLYING_TIME		 3500
#define MARIO_TIME_BACK_TO_WORLDMAP	2000
#define MARIO_TIME_SLIDE_UP_DOWN 3000
#define MARIO_TIME_TRANSFORM 1000
#define MARIO_TIME_FIRING 200
#define	MARIO_DIFFERENCE_HEIGHT	12

#define MARIO_BIG_BBOX_WIDTH  15
#define MARIO_BIG_BBOX_HEIGHT 27
#define MARIO_SMALL_BBOX_WIDTH  13
#define MARIO_SMALL_BBOX_HEIGHT 15
#define MARIO_TAIL_BBOX_WIDTH  21
#define MARIO_TAIL_BBOX_HEIGHT 27
#define MARIO_FIRE_BBOX_WIDTH  14
#define MARIO_FIRE_BBOX_HEIGHT 27

#define SPEECH_ADDTION_PER_LEVEL	0.002f
#define MARIO_MAX_SPEED	0.3f
#define MARIO_INERTIA 0.03f
#define MARIO_FLYING_SPEED 0.075f
#define MARIO_TAIL_FALL_SPEED 0.05f

#define MARIO_SPRITE_SCORE_UP_100	60150
#define MARIO_SPRITE_SCORE_UP_200	60151
#define MARIO_SPRITE_SCORE_UP_400	60152
#define MARIO_SPRITE_SCORE_UP_800	60153
#define MARIO_SPRITE_SCORE_UP_1000	60154
#define MARIO_SPRITE_SCORE_UP_2000	60155
#define MARIO_SPRITE_SCORE_UP_4000	60156
#define MARIO_SPRITE_SCORE_UP_8000	60157
#define MARIO_SPRITE_SCORE_UP_LV_UP	60158

#define POS_X_TUNNEL_MAP_1 1330
#define POS_Y_TUNNEL_MAP_1 1050
#define POS_X_OUT_OF_TUNNEL_MAP_1 2330
#define POS_Y_OUT_OF_TUNNEL_MAP_1 122
#define POS_X_SCENE_END_MAP_4 2200
#define POS_Y_SCENE_END_MAP_4 300
#define POS_X_EDGE_MAP_4 2055

//BELL
#define BELL_BBOX_WIDTH  16
#define BELL_BBOX_HEIGHT 16
#define BELL_BBOX_HEIGHT_PRESSED 7

#define BELL_STATE_DISAPPEAR 100
#define BELL_STATE_SHOW 200
#define BELL_STATE_PRESSED 300

#define BELL_ANI_SHOW 0
#define BELL_ANI_PRESSED 1

// BOOMERANG

#define BOOMERANG_BBOX_WIDTH  16
#define BOOMERANG_BBOX_HEIGHT 16


#define MAX_TIME_STAGE_1	500
#define	MAX_TIME_STAGE_2	1200
#define	MAX_TIME_STAGE_3	1600
#define MAX_TIME_STAGE_4	4000
#define	TIME_SWITCH_STATE	250
#define BOOMERANG_VX	0.1f
#define BOOMERANG_VY_STAGE_1_3	0.00006f
#define BOOMERANG_VY_STAGE_2	0.00015f

#define BOOMERANG_ANI_FLY_RIGHT		0
#define BOOMERANG_ANI_FLY_LEFT		1
// BOOMERANG ENEMY

#define  BOOMERANG_ENEMY_BBOX_WIDTH		16
#define  BOOMERANG_ENEMY_BBOX_HEIGHT	24

#define  BOOMERANG_ENEMY_STATE_IDLE				0
#define  BOOMERANG_ENEMY_STATE_MOVE_FORWARD		100
#define  BOOMERANG_ENEMY_STATE_MOVE_BACKWARD    200
#define	 BOOMERANG_ENEMY_STATE_DIE				300

#define BOOMERANG_ENEMY_GRAVITY		0.002f


#define BOOMERANG_ENEMY_ANI_NORMAL_RIGHT				0
#define BOOMERANG_ENEMY_ANI_THROW_BOOMERANG_RIGHT		1
#define BOOMERANG_ENEMY_ANI_DIE_RIGHT					2
#define BOOMERANG_ENEMY_ANI_DIE_LEFT					3
#define BOOMERANG_ENEMY_ANI_NORMAL_LEFT					4	
#define BOOMERANG_ENEMY_ANI_THROW_BOOMERANG_LEFT		5


#define	TIME_RENDER_ANI_THROW	300
#define	TIME_TO_THROW_BOOM_1	900
#define	TIME_TO_THROW_BOOM_2	3300
#define TIME_SWITCH_STATE_1		700	
#define TIME_SWITCH_STATE_2		2000
#define TIME_SWITCH_STATE_3		2700	
#define TIME_SWITCH_STATE_4		4000
#define	BOOMERANG_ENEMY_VX	0.03f
// BREAKABLEBRICK

#define BRICK_BBOX_WIDTH  16
#define BRICK_BBOX_HEIGHT 16

#define BREAKABLE_BRICK_NORMAL 111
#define BREAKABLE_BRICK_BELL 222

#define BREAKABLE_STATE_SHOW 444
#define BREAKABLE_STATE_BROKEN	555
#define BREAKABLE_STATE_EMPTY_BOX	666
#define BREAKABLE_STATE_COIN	777
#define BREAKABLE_STATE_DISAPPEAR 888

#define BREAKABLE_ANI_NORMAL 0
#define BREAKABLE_ANI_EMPTY_BOX 1
#define BREAKABLE_ANI_COIN 2

#define TIME_REVIVE_FROM_COIN 3000
// BREAKABLEBRICKANIMATION


#define BREAKABLE_BRICK_ANIMATION_STATE_IDLE	0
#define BREAKABLE_BRICK_ANIMATION_STATE_MOVE	100

#define BREAKABLE_BRICK_ANIMATION_GRAVITY		0.002f

#define BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_TOP			111
#define BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_TOP		222
#define BREAKABLE_BRICK_ANIMATION_TYPE_RIGHT_BOTTOM		333
#define BREAKABLE_BRICK_ANIMATION_TYPE_LEFT_BOTTOM		444

//BRICK

#define BRICK_BBOX_WIDTH  16
#define BRICK_BBOX_HEIGHT 16
// COIN

#define COIN_BBOX_WIDTH  10
#define COIN_BBOX_HEIGHT 14


#define COIN_STATE_IDLE		0
#define COIN_STATE_UP		100
#define COIN_STATE_DOWN		200

#define COIN_NORMAL			222
#define COIN_CAN_TOSS		333

#define TIME_COIN_ON_AIR 250
// FIREBULLET

#define BULLET_BBOX_WIDTH	9
#define BULLET_BBOX_HEIGHT 9

#define BULLET_GRAVITY 0.0009f
#define BULLET_FLYING_SPEED 0.2f

#define BULLET_STATE_FLYING 100
#define BULLET_STATE_DISAPPEARING 200

#define BULLET_ANI_FLYING_RIGHT 0
#define BULLET_ANI_FLYING_LEFT 1
// FLOATINGWOOD

#define FLOATING_WOOD_BBOX_WIDTH		48
#define  FLOATING_WOOD_BBOX_HEIGHT		16



#define   FLOATING_WOOD_STATE_NORMAL		0
#define   FLOATING_WOOD_STATE_DOWN			100

#define	  FLOATING_WOOD_STATE_NORMAL_SPEED   -0.03f
#define   FLOATING_WOOD_STATE_DOWN_SPEED	   0.06f
//
// FLOWER

#define FLOWER_RED_BBOX_WIDTH  16
#define FLOWER_RED_BBOX_HEIGHT 32

#define FLOWER_GREEN_BBOX_WIDTH  16
#define FLOWER_GREEN_BBOX_HEIGHT 24

#define FLOWER_GREEN_CAN_SHOOT_BBOX_WIDTH  16
#define FLOWER_GREEN_CAN_SHOOT_BBOX_HEIGHT 24

#define FLOWER_RED_ANI_LEFT			0
#define FLOWER_RED_ANI_RIGHT		1
#define FLOWER_RED_ANI_LEFT_IDLE	2
#define FLOWER_RED_ANI_RIGHT_IDLE	3
#define FLOWER_GREEN_ANI			4
#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT			5
#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT		6
#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT_IDLE	7
#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT_IDLE	8
#define FLOWER_RED_ANI_LEFT_UP						9
#define FLOWER_RED_ANI_RIGHT_UP						10
#define FLOWER_RED_ANI_LEFT_IDLE_UP					11
#define FLOWER_RED_ANI_RIGHT_IDLE_UP				12
#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT_UP			13
#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT_UP			14
#define FLOWER_GREEN_CAN_SHOOT_ANI_LEFT_IDLE_UP		15
#define FLOWER_GREEN_CAN_SHOOT_ANI_RIGHT_IDLE_UP	16

#define FLOWER_RED				100
#define FLOWER_GREEN			200
#define FLOWER_GREEN_CAN_SHOOT  300 


#define FLOWER_RED_TOP_LIMIT			72
#define FLOWER_RED_BOT_LIMIT			117
#define RED_TIME_SHOWING_LIMIT			3000

#define FLOWER_GREEN_TOP_LIMIT			96
#define FLOWER_GREEN_BOT_LIMIT			126
#define GREEN_TIME_SHOWING_LIMIT		2000


#define FLOWER_GREEN_CAN_SHOOT_TOP_LIMIT		79
#define FLOWER_GREEN_CAN_SHOOT_BOT_LIMIT		126
#define GREEN_CAN_SHOOT_TIME_SHOWING_LIMIT		3000
// FLOWER BULLET

#define FLOWER_BULLET_BBOX_WIDTH  8
#define FLOWER_BULLET_BBOX_HEIGHT 9

#define FLOWER_BULLET_X_LIMIT		72


#define FLOWER_BULLET_FLYING_SPEED		0.05f 

#define FLOWER_BULLET_STATE_FLYING		100
#define FLOWER_BULLET_STATE_HIDDEN		200

#define FLOWER_BULLET_ANI			0
// game

#define DIRECTINPUT_VERSION 0x0800
#define KEYBOARD_BUFFER_SIZE 1024
//GAMEOBJECT

#define ID_TEX_BBOX -100		// special texture to draw object bounding box
// GOOMBA

#define GOOMBA_WALKING_SPEED 0.05f
#define GOOMBA_JUMP_SPEED		0.35f
#define GOOMBA_TIME_JUMPING		900

#define GOOMBA_NORMAL_BBOX_WIDTH 16
#define GOOMBA_NORMAL_BBOX_HEIGHT 16
#define GOOMBA_BBOX_HEIGHT_DIE 9
#define GOOMBA_BBOX_FLY_WIDTH	19
#define GOOMBA_BBOX_FLY_HEIGHT_EAR_DOWN 20
#define GOOMBA_BBOX_FLY_HEIGHT_EAR_UP 24

#define GOOMBA_STATE_WALKING 100
#define GOOMBA_STATE_DIE 200
#define	GOOMBA_STATE_DISAPPEAR	300
#define GOOMBA_STATE_DIE_BY_KICK	400
#define GOOMBA_STATE_GEARING 500
#define GOOMBA_STATE_FLYING 600

#define GOOMBA_ANI_ORANGE_WALKING 0
#define GOOMBA_ANI_ORANGE_DIE 1
#define GOOMBA_ANI_RED_FLY_WALKING 2
#define GOOMBA_ANI_RED_DIE 3
#define GOOMBA_ANI_RED_WALKING	4
#define GOOMBA_ANI_RED_GEARING 5
#define GOOMBA_ANI_RED_FLYING	6

#define	GOOMBA_DYING_TIME 300
#define GOOMBA_TIME_WALKING 300
#define GOOMBA_TIME_GEARING 600
#define GOOMBA_TIME_FLYING 900

#define	GOOMBA_TYPE_ORANGE 1
#define	GOOMBA_TYPE_RED_FLY 2
#define	GOOMBA_TYPE_RED_WALK 3
#define GOOMBA_DIE_DEFLECT_SPEED 0.5f

#define GOOMBA_JUMP_DEFLECT_SPEED 0.35f
//GRID

#define GRID_SECTION_SETTINGS	1
#define GRID_SECTION_OBJECTS	2
#define MAX_GRID_LINE 1024
// HIT EFFECT

#define HIT_EFFECT_STATE_IDLE	0




#define HIT_EFFECT_TURN_TAIL			100
#define HIT_EFFECT_FIRE_BULLET			200	




#define HIT_EFFECT_TURN_TAIL_ANI_RIGHT			0
#define HIT_EFFECT_TURN_TAIL_ANI_LEFT			1
#define HIT_EFFECT_ANI_FIRE_BULLET				2

//HUDPANEL

#define HUD_SPRITE_PANEL_INFO	60100
#define HUD_SPRITE_PANEL_ITEM	60101
#define HUD_SPRITE_ICON_MARIO	60102
#define HUD_SPRITE_ICON_LUGI	60103
#define HUD_SPRITE_POWERMELTER_FILLED_ARROW	60104
#define HUD_SPRITE_POWERMELTER_FILLED_LIGHT	60105
#define HUD_SPRITE_POWERMELTER_EMPTY_ARROW	60106
#define HUD_SPRITE_POWERMELTER_EMPTY_LIGHT	60107
#define HUD_SPRITE_EMPTY_CARD	60108
#define HUD_SPRITE_MUSHROOM_CARD	60109
#define HUD_SPRITE_FLOWER_CARD	60110
#define HUD_SPRITE_STAR_CARD	60111
#define HUD_SPRITE_0	60112
#define HUD_SPRITE_1	60113
#define HUD_SPRITE_2	60114
#define HUD_SPRITE_3	60115
#define HUD_SPRITE_4	60116
#define HUD_SPRITE_5	60117
#define HUD_SPRITE_6	60118
#define HUD_SPRITE_7	60119
#define HUD_SPRITE_8	60120
#define HUD_SPRITE_9	60121
#define HUD_SPRITE_A	60122
#define HUD_SPRITE_B	60123
#define HUD_SPRITE_C	60124
#define HUD_SPRITE_D	60125
#define HUD_SPRITE_E	60126
#define HUD_SPRITE_F	60127
#define HUD_SPRITE_G	60128
#define HUD_SPRITE_H	60129
#define HUD_SPRITE_I	60130
#define HUD_SPRITE_J	60131
#define HUD_SPRITE_K	60132
#define HUD_SPRITE_L	60133
#define HUD_SPRITE_M	60134
#define HUD_SPRITE_N	60135
#define HUD_SPRITE_O	60136
#define HUD_SPRITE_P	60137
#define HUD_SPRITE_Q	60138
#define HUD_SPRITE_R	60139
#define HUD_SPRITE_S	60140
#define HUD_SPRITE_T	60141
#define HUD_SPRITE_U	60142
#define HUD_SPRITE_V	60143
#define HUD_SPRITE_W	60144
#define HUD_SPRITE_X	60145
#define HUD_SPRITE_Y	60146
#define HUD_SPRITE_Z	60147
#define HUD_SPRITE_BLACK_BACKGROUND	60148

//KOOPAS

#define KOOPAS_WALKING_SPEED 0.03f
#define KOOPAS_SPINNING_SPEED 0.3f
#define	KOOPAS_SHELL_DEFLECT_SPEED 0.25f

#define KOOPAS_TYPE_GREEN_WALK 1
#define KOOPAS_TYPE_GREEN_FLY 2
#define KOOPAS_TYPE_RED_WALK 3
#define KOOPAS_TYPE_RED_FLY 4


#define KOOPAS_STATE_WALKING 100
#define KOOPAS_STATE_DIE 200
#define	KOOPAS_STATE_SHELL	300
#define	KOOPAS_STATE_SPINNING 400
#define KOOPAS_STATE_FLYING_UP_DOWN 500

//#define KOOPAS_ANI_GREEN_WALK_WALKING_LEFT 0
//#define KOOPAS_ANI_GREEN_WALK_WALKING_RIGHT 1
//#define	KOOPAS_ANI_GREEN_FLY_WALKING_LEFT 2
//#define	KOOPAS_ANI_GREEN_SHELL_PRONE 3
//#define	KOOPAS_ANI_GREEN_SHELL_UPWARD 4
//#define KOOPAS_ANI_RED_WALK_WALKING_LEFT 5
//#define KOOPAS_ANI_RED_FLY_WALKING_LEFT 6
//#define KOOPAS_ANI_RED_FLY_SHELL_UP 7

#define	KOOPAS_GRAVITY	0.002f


#define KOOPAS_BBOX_WIDTH 15
#define KOOPAS_BBOX_HEIGHT 26
#define KOOPAS_BBOX_HEIGHT_SHELL 14
#define KOOPAS_BBOX_HEIGHT_DIE 16

#define KOOPAS_ANI_GREEN_WALKING_LEFT  0
#define KOOPAS_ANI_GREEN_WALKING_RIGHT 1
#define KOOPAS_ANI_GREEN_FLYING_LEFT   2

#define KOOPAS_ANI_GREEN_SHELL_PRONE	3
#define KOOPAS_ANI_GREEN_SHELL_UPWARD	  4	
#define KOOPAS_ANI_RED_WALKING_LEFT   5
#define KOOPAS_ANI_RED_WALKING_RIGHT	6
#define KOOPAS_ANI_RED_FLYING_LEFT	7
#define KOOPAS_ANI_RED_SHELL_PRONE	8
#define KOOPAS_ANI_GREEN_SPINNING  9
#define KOOPAS_ANI_RED_ANI_SPINNING	  10
#define KOOPAS_XANH_ANI_REVIVING	  11	
#define KOOPAS_RED_ANI_REVIVING		  12
#define KOOPAS_RED_MAI_ANI_NGUA		  13
#define KOOPAS_XANH_ANI_REVIVING_NGUA			14
#define KOOPAS_RED_ANI_REVIVING_NGUA			15
#define KOOPAS_BLACK_UP							16
#define KOOPAS_BLACK_NGUA						17
#define KOOPAS_XANH_ANI_WALKING_RIGHT_FASTER	18
#define KOOPAS_XANH_MAI_ANI_SPINNING_NGUA		19
#define KOOPAS_RED_MAI_ANI_SPINNING_NGUA		20
#define KOOPAS_ANI_RED_FLYING_LEFT_NICE	21
#define KOOPAS_DIE_DEFLECT_SPEED 0.75f
#define KOOPAS_FLY_DEFLECT_SPEED 0.4f
#define KOOPAS_PERIODIC_TIME_FLY 1000

#define KOOPAS_HOLDING 1
#define	KOOPAS_NOT_HOLDING 0

#define KOOPAS_TIME_REVIVE 5000
#define KOOPAS_TIME_ABOUT_TO_REVIVE 3000
// LEAF

//#define LEAF_BBOX_WIDTH		16
//#define LEAF_BBOX_HEIGHT	14
#define LEAF_BBOX_WIDTH		18
#define LEAF_BBOX_HEIGHT	16

#define LEAF_STATE_IDLE		150
#define LEAF_STATE_UP		100
#define LEAF_STATE_DOWN		200



#define LEAF_ANI_LEFT		0
#define LEAF_ANI_RIGHT		1
//MAP

#define TILE_WIDTH 32
#define TILE_HEIGHT 32
//MENUGAME

#define MENU_GAME_ANI_1_PLAYER	0
#define MENU_GAME_ANI_2_PLAYER	1
//MUSHROOM

#define MUSHROOM_BBOX_WIDTH		16
#define MUSHROOM_BBOX_HEIGHT	16

#define MUSHROOM_STATE_IDLE		0
#define MUSHROOM_STATE_UP		100
#define MUSHROOM_STATE_MOVE		200

#define MUSHROOM_GRAVITY		0.002f
#define MUSHROOM_RED			567
#define MUSHROOM_GREEN			678

#define MUSHROOM_ANI_RED		0
#define MUSHROOM_ANI_GREEN		1
//PIPE

#define PIPE_BBOX_WIDTH  32
#define PIPE_BBOX_HEIGHT 16

#define PIPE_BBOX_WIDTH_NORMAL	16


#define PIPE_TYPE_NORMAL	100
#define PIPE_TYPE_DOWN		200
#define PIPE_TYPE_UP		300
//QUESTION BRICK

#define QUESTION_BRICK_BBOX_WIDTH  16
#define QUESTION_BRICK_BBOX_HEIGHT 16

#define QUESTION_BRICK_STATE_USED 100

#define QUESTION_BRICK_ANI_ALIVE	0
#define QUESTION_BRICK_ANI_DEAD		1
#define QUESTION_BRICK_ANI_NEW_TYPE	2

#define QUESTION_BRICK_NORMAL				666
#define QUESTION_BRICK_HAVE_LEAF			777
#define QUESTION_BRICK_JUST_HAVE_MUSHROOM	888
#define QUESTION_BRICK_HAVE_MULTI_COIN	999
//RECTANGLE

#define RECTANGLE_BBOX_WIDTH  16
#define RECTANGLE_BBOX_HEIGHT 16
// SCOREUP

#define SCORE_STATE_IDLE	0
#define SCORE_STATE_UP		100


#define SCORE_TYPE_100			100
#define SCORE_TYPE_200			200	
#define SCORE_TYPE_400			400
#define SCORE_TYPE_800			800
#define SCORE_TYPE_1000			1000
#define SCORE_TYPE_2000			2000
#define SCORE_TYPE_4000			4000
#define SCORE_TYPE_8000			8000
#define SCORE_TYPE_1LIFE		9999




#define SCORE_100_ANI			0
#define SCORE_200_ANI			1	
#define SCORE_400_ANI			2
#define SCORE_800_ANI			3
#define SCORE_1000_ANI			4
#define SCORE_2000_ANI			5
#define SCORE_4000_ANI			6
#define SCORE_8000_ANI			7
#define SCORE_1LIFE_ANI			8
//SCROLLINGSTAGE

#define SCROLLING_STAGE_STATE_IDLE		0
#define SCROLLING_STAGE_STATE_UP		100
// SPECIALITEM

#define SPECIAL_ITEM_BBOX_WIDTH		16
#define SPECIAL_ITEM_BBOX_HEIGHT	16

#define SPECIAL_ITEM_STATE_FLOWER_IDLE			100
#define SPECIAL_ITEM_STATE_MUSHROOM_IDLE		200
#define SPECIAL_ITEM_STATE_STAR_IDLE			300

#define SPECIAL_ITEM_STATE_FLOWER_UP			400
#define SPECIAL_ITEM_STATE_MUSHROOM_UP			500
#define SPECIAL_ITEM_STATE_STAR_UP				600

#define SPECIAL_ITEM_STATE_FLOWER_IDLE_ANI			0
#define SPECIAL_ITEM_STATE_MUSHROOM_IDLE_ANI		1
#define SPECIAL_ITEM_STATE_STAR_IDLE_ANI			2

#define SPECIAL_ITEM_STATE_FLOWER_UP_ANI			3
#define SPECIAL_ITEM_STATE_MUSHROOM_UP_ANI			4
#define SPECIAL_ITEM_STATE_STAR_UP_ANI				5
//WORLDMAPOBJECT

#define MARIO_STATE_MOVE_RIGHT		100
#define MARIO_STATE_MOVE_LEFT		200
#define MARIO_STATE_MOVE_UP			300
#define MARIO_STATE_MOVE_DOWN		400
#define MARIO_STATE_CANT_MOVE		500

#define GOLD_DIGGER_STATE_WALKING_RIGHT	600
#define GOLD_DIGGER_STATE_WALKING_LEFT	700

#define WORLD_MAP_TYPE_ANI_BUSH			0
#define WORLD_MAP_TYPE_ANI_HELP			1
#define WORLD_MAP_TYPE_ANI_GOLD_DIGGER_WALK_RIGHT	2
#define WORLD_MAP_TYPE_ANI_MARIO		3
#define WORLD_MAP_TYPE_ANI_GOLD_DIGGER_WALK_LEFT	4

#define WORLD_MAP_TYPE_MARIO		11
#define WORLD_MAP_TYPE_HELP			22
#define WORLD_MAP_TYPE_GOLD_DIGGER	33
#define WORLD_MAP_TYPE_BUSH			44

class define
{

};

